# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10, 12]
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup Node.js
    - name: "Install Node.js"
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
        
    # Setup yarn
    - name: "Install Yarn"
      run: "npm install -g yarn"
    
    # Setup Surge
    - name: "Install Surge"
      run: "npm install -g surge"
      
    # Build
    - name: "Build"
      run: |
        yarn install
        yarn build
    
    - name: "Deploy to surge"
      run: |
        cd build
        surge ./ react-static-job-listings.surge.sh --token ${{ secrets.SURGE_TOKEN }}
